pipeline:
  identifier: Build_rahultyagi624_demo_angular_app_1704341370138
  name: Build demo-angular-app
  orgIdentifier: default
  projectIdentifier: new_deo4
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: rahultyagi624/demo-angular-app
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |
                      cd root/
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
